# Game source lists from NBlood 497385d6; regenerate after upstream source-list changes.

GAME_SOURCES_blood := source/blood/src/blood.cpp \
  source/blood/src/actor.cpp \
  source/blood/src/ai.cpp \
  source/blood/src/aibat.cpp \
  source/blood/src/aibeast.cpp \
  source/blood/src/aiboneel.cpp \
  source/blood/src/aiburn.cpp \
  source/blood/src/aicaleb.cpp \
  source/blood/src/aicerber.cpp \
  source/blood/src/aicult.cpp \
  source/blood/src/aigarg.cpp \
  source/blood/src/aighost.cpp \
  source/blood/src/aigilbst.cpp \
  source/blood/src/aihand.cpp \
  source/blood/src/aihound.cpp \
  source/blood/src/aiinnoc.cpp \
  source/blood/src/aipod.cpp \
  source/blood/src/airat.cpp \
  source/blood/src/aispid.cpp \
  source/blood/src/aitchern.cpp \
  source/blood/src/aizomba.cpp \
  source/blood/src/aizombf.cpp \
  source/blood/src/asound.cpp \
  source/blood/src/barf.cpp \
  source/blood/src/callback.cpp \
  source/blood/src/choke.cpp \
  source/blood/src/common.cpp \
  source/blood/src/config.cpp \
  source/blood/src/controls.cpp \
  source/blood/src/credits.cpp \
  source/blood/src/db.cpp \
  source/blood/src/demo.cpp \
  source/blood/src/dude.cpp \
  source/blood/src/endgame.cpp \
  source/blood/src/eventq.cpp \
  source/blood/src/fire.cpp \
  source/blood/src/fx.cpp \
  source/blood/src/gamemenu.cpp \
  source/blood/src/gameutil.cpp \
  source/blood/src/getopt.cpp \
  source/blood/src/gfx.cpp \
  source/blood/src/gib.cpp \
  source/blood/src/globals.cpp \
  source/blood/src/gui.cpp \
  source/blood/src/inifile.cpp \
  source/blood/src/iob.cpp \
  source/blood/src/levels.cpp \
  source/blood/src/loadsave.cpp \
  source/blood/src/map2d.cpp \
  source/blood/src/menu.cpp \
  source/blood/src/messages.cpp \
  source/blood/src/mirrors.cpp \
  source/blood/src/misc.cpp \
  source/blood/src/network.cpp \
  source/blood/src/osdcmd.cpp \
  source/blood/src/player.cpp \
  source/blood/src/qav.cpp \
  source/blood/src/qheap.cpp \
  source/blood/src/replace.cpp \
  source/blood/src/resource.cpp \
  source/blood/src/screen.cpp \
  source/blood/src/sectorfx.cpp \
  source/blood/src/seq.cpp \
  source/blood/src/sfx.cpp \
  source/blood/src/sound.cpp \
  source/blood/src/tile.cpp \
  source/blood/src/trig.cpp \
  source/blood/src/triggers.cpp \
  source/blood/src/view.cpp \
  source/blood/src/warp.cpp \
  source/blood/src/weapon.cpp

GAME_SOURCES_duke3d := source/duke3d/src/actors.cpp \
  source/duke3d/src/anim.cpp \
  source/duke3d/src/cheats.cpp \
  source/duke3d/src/cmdline.cpp \
  source/duke3d/src/common.cpp \
  source/duke3d/src/config.cpp \
  source/duke3d/src/demo.cpp \
  source/duke3d/src/dnames.cpp \
  source/duke3d/src/game.cpp \
  source/duke3d/src/gamedef.cpp \
  source/duke3d/src/gameexec.cpp \
  source/duke3d/src/gamestructures.cpp \
  source/duke3d/src/gamevars.cpp \
  source/duke3d/src/global.cpp \
  source/duke3d/src/grpscan.cpp \
  source/duke3d/src/input.cpp \
  source/duke3d/src/menus.cpp \
  source/duke3d/src/network.cpp \
  source/duke3d/src/osdcmds.cpp \
  source/duke3d/src/osdfuncs.cpp \
  source/duke3d/src/player.cpp \
  source/duke3d/src/premap.cpp \
  source/duke3d/src/rts.cpp \
  source/duke3d/src/savegame.cpp \
  source/duke3d/src/sbar.cpp \
  source/duke3d/src/screens.cpp \
  source/duke3d/src/sector.cpp \
  source/duke3d/src/sounds.cpp \
  source/duke3d/src/text.cpp \
  source/duke3d/src/winbits.cpp

GAME_SOURCES_sw := source/sw/src/actor.cpp \
  source/sw/src/ai.cpp \
  source/sw/src/anim.cpp \
  source/sw/src/border.cpp \
  source/sw/src/break.cpp \
  source/sw/src/bunny.cpp \
  source/sw/src/cache.cpp \
  source/sw/src/cheats.cpp \
  source/sw/src/colormap.cpp \
  source/sw/src/common.cpp \
  source/sw/src/config.cpp \
  source/sw/src/console.cpp \
  source/sw/src/coolg.cpp \
  source/sw/src/coolie.cpp \
  source/sw/src/copysect.cpp \
  source/sw/src/demo.cpp \
  source/sw/src/draw.cpp \
  source/sw/src/eel.cpp \
  source/sw/src/game.cpp \
  source/sw/src/girlninj.cpp \
  source/sw/src/goro.cpp \
  source/sw/src/grpscan.cpp \
  source/sw/src/hornet.cpp \
  source/sw/src/interp.cpp \
  source/sw/src/interpsh.cpp \
  source/sw/src/interpso.cpp \
  source/sw/src/inv.cpp \
  source/sw/src/jplayer.cpp \
  source/sw/src/jsector.cpp \
  source/sw/src/jweapon.cpp \
  source/sw/src/lava.cpp \
  source/sw/src/light.cpp \
  source/sw/src/mclip.cpp \
  source/sw/src/mdastr.cpp \
  source/sw/src/menus.cpp \
  source/sw/src/miscactr.cpp \
  source/sw/src/morph.cpp \
  source/sw/src/network.cpp \
  source/sw/src/ninja.cpp \
  source/sw/src/panel.cpp \
  source/sw/src/player.cpp \
  source/sw/src/predict.cpp \
  source/sw/src/quake.cpp \
  source/sw/src/ripper.cpp \
  source/sw/src/ripper2.cpp \
  source/sw/src/rooms.cpp \
  source/sw/src/rotator.cpp \
  source/sw/src/rts.cpp \
  source/sw/src/save.cpp \
  source/sw/src/saveable.cpp \
  source/sw/src/scrip2.cpp \
  source/sw/src/sector.cpp \
  source/sw/src/serp.cpp \
  source/sw/src/setup.cpp \
  source/sw/src/skel.cpp \
  source/sw/src/skull.cpp \
  source/sw/src/slidor.cpp \
  source/sw/src/sounds.cpp \
  source/sw/src/spike.cpp \
  source/sw/src/sprite.cpp \
  source/sw/src/sumo.cpp \
  source/sw/src/swconfig.cpp \
  source/sw/src/sync.cpp \
  source/sw/src/text.cpp \
  source/sw/src/track.cpp \
  source/sw/src/vator.cpp \
  source/sw/src/vis.cpp \
  source/sw/src/wallmove.cpp \
  source/sw/src/warp.cpp \
  source/sw/src/weapon.cpp \
  source/sw/src/zilla.cpp \
  source/sw/src/zombie.cpp

GAME_SOURCES_rr := source/rr/src/game.cpp \
  source/rr/src/global.cpp \
  source/rr/src/actors.cpp \
  source/rr/src/gamedef.cpp \
  source/rr/src/gameexec.cpp \
  source/rr/src/gamevars.cpp \
  source/rr/src/player.cpp \
  source/rr/src/premap.cpp \
  source/rr/src/sector.cpp \
  source/rr/src/anim.cpp \
  source/rr/src/common.cpp \
  source/rr/src/config.cpp \
  source/rr/src/demo.cpp \
  source/rr/src/input.cpp \
  source/rr/src/menus.cpp \
  source/rr/src/namesdyn.cpp \
  source/rr/src/net.cpp \
  source/rr/src/savegame.cpp \
  source/rr/src/rts.cpp \
  source/rr/src/osdfuncs.cpp \
  source/rr/src/osdcmds.cpp \
  source/rr/src/grpscan.cpp \
  source/rr/src/sounds.cpp \
  source/rr/src/soundsdyn.cpp \
  source/rr/src/cheats.cpp \
  source/rr/src/sbar.cpp \
  source/rr/src/screentext.cpp \
  source/rr/src/screens.cpp \
  source/rr/src/cmdline.cpp \
  source/rr/src/rrdh.cpp \
  source/rr/src/filestream.cpp \
  source/rr/src/playmve.cpp

GAME_SOURCES_exhumed := source/exhumed/src/aistuff.cpp \
  source/exhumed/src/anims.cpp \
  source/exhumed/src/anubis.cpp \
  source/exhumed/src/bubbles.cpp \
  source/exhumed/src/bullet.cpp \
  source/exhumed/src/cd.cpp \
  source/exhumed/src/common.cpp \
  source/exhumed/src/config.cpp \
  source/exhumed/src/enginesubs.cpp \
  source/exhumed/src/exhumed.cpp \
  source/exhumed/src/exscript.cpp \
  source/exhumed/src/fish.cpp \
  source/exhumed/src/grenade.cpp \
  source/exhumed/src/grpscan.cpp \
  source/exhumed/src/gun.cpp \
  source/exhumed/src/init.cpp \
  source/exhumed/src/input.cpp \
  source/exhumed/src/items.cpp \
  source/exhumed/src/lavadude.cpp \
  source/exhumed/src/light.cpp \
  source/exhumed/src/lighting.cpp \
  source/exhumed/src/lion.cpp \
  source/exhumed/src/map.cpp \
  source/exhumed/src/memorystream.cpp \
  source/exhumed/src/menu.cpp \
  source/exhumed/src/mono.cpp \
  source/exhumed/src/move.cpp \
  source/exhumed/src/movie.cpp \
  source/exhumed/src/mummy.cpp \
  source/exhumed/src/network.cpp \
  source/exhumed/src/object.cpp \
  source/exhumed/src/osdcmds.cpp \
  source/exhumed/src/player.cpp \
  source/exhumed/src/queen.cpp \
  source/exhumed/src/ra.cpp \
  source/exhumed/src/ramses.cpp \
  source/exhumed/src/random.cpp \
  source/exhumed/src/rat.cpp \
  source/exhumed/src/record.cpp \
  source/exhumed/src/rex.cpp \
  source/exhumed/src/roach.cpp \
  source/exhumed/src/runlist.cpp \
  source/exhumed/src/save.cpp \
  source/exhumed/src/scorp.cpp \
  source/exhumed/src/sequence.cpp \
  source/exhumed/src/serial.cpp \
  source/exhumed/src/set.cpp \
  source/exhumed/src/snake.cpp \
  source/exhumed/src/sound.cpp \
  source/exhumed/src/spider.cpp \
  source/exhumed/src/status.cpp \
  source/exhumed/src/stream.cpp \
  source/exhumed/src/switch.cpp \
  source/exhumed/src/text2.cpp \
  source/exhumed/src/timer.cpp \
  source/exhumed/src/trigdat.cpp \
  source/exhumed/src/version.cpp \
  source/exhumed/src/view.cpp \
  source/exhumed/src/wasp.cpp

GAME_SOURCES_tekwar := source/tekwar/src/b5compat.cpp \
  source/tekwar/src/common.cpp \
  source/tekwar/src/config.cpp \
  source/tekwar/src/grpscan.cpp \
  source/tekwar/src/osdcmds.cpp \
  source/tekwar/src/tekcdr.cpp \
  source/tekwar/src/tekchng.cpp \
  source/tekwar/src/tekgame.cpp \
  source/tekwar/src/tekgun.cpp \
  source/tekwar/src/tekldsv.cpp \
  source/tekwar/src/tekmap.cpp \
  source/tekwar/src/tekmsc.cpp \
  source/tekwar/src/tekprep.cpp \
  source/tekwar/src/teksmk.cpp \
  source/tekwar/src/teksnd.cpp \
  source/tekwar/src/tekspr.cpp \
  source/tekwar/src/tekstat.cpp \
  source/tekwar/src/tektag.cpp \
  source/tekwar/src/tektxt.cpp \
  source/tekwar/src/tekver.cpp

GAME_SOURCES_witchaven := source/witchaven/src/animation.cpp \
  source/witchaven/src/common.cpp \
  source/witchaven/src/config.cpp \
  source/witchaven/src/effects.cpp \
  source/witchaven/src/enginesubs.cpp \
  source/witchaven/src/grpscan.cpp \
  source/witchaven/src/input.cpp \
  source/witchaven/src/menu.cpp \
  source/witchaven/src/network.cpp \
  source/witchaven/src/objects.cpp \
  source/witchaven/src/osdcmds.cpp \
  source/witchaven/src/player.cpp \
  source/witchaven/src/sound.cpp \
  source/witchaven/src/tags.cpp \
  source/witchaven/src/view.cpp \
  source/witchaven/src/witchaven.cpp

GAME_SOURCES_kenbuild := source/kenbuild/src/common.cpp \
  source/kenbuild/src/config.cpp \
  source/kenbuild/src/kdmeng.cpp \
  source/kenbuild/src/game.cpp

GAME_SOURCES_rr += $(wildcard source/rr/src/n64/*.cpp)
